Traceback (most recent call last):
  File "/Users/gmatteo/miniconda3/envs/env3.8/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/gmatteo/miniconda3/envs/env3.8/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/gmatteo/miniconda3/envs/env3.8/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/gmatteo/miniconda3/envs/env3.8/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/gmatteo/miniconda3/envs/env3.8/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Users/gmatteo/miniconda3/envs/env3.8/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/gmatteo/miniconda3/envs/env3.8/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/gmatteo/miniconda3/envs/env3.8/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
robot = abilab.GsrRobot.from_dir("flow_al_relax_tsmear_nkpt")
robot
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m<ipython-input-10-d9233a9f88ec>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mrobot[0m [0;34m=[0m [0mabilab[0m[0;34m.[0m[0mGsrRobot[0m[0;34m.[0m[0mfrom_dir[0m[0;34m([0m[0;34m"flow_al_relax_tsmear_nkpt"[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mrobot[0m[0;34m[0m[0m

[0;32m~/git_repos/abipy/abipy/abio/robots.py[0m in [0;36mfrom_dir[0;34m(cls, top, walk, abspath)[0m
[1;32m     90[0m             [0mabspath[0m[0;34m:[0m [0;32mTrue[0m [0;32mif[0m [0mpaths[0m [0;32min[0m [0mindex[0m [0mshould[0m [0mbe[0m [0mabsolute[0m[0;34m.[0m [0mDefault[0m[0;34m:[0m [0mRelative[0m [0mto[0m[0;31m [0m[0;31m`[0m[0mtop[0m[0;31m`[0m[0;34m.[0m[0;34m[0m[0m
[1;32m     91[0m         """
[0;32m---> 92[0;31m         [0mnew[0m [0;34m=[0m [0mcls[0m[0;34m([0m[0;34m*[0m[0mcls[0m[0;34m.[0m[0m_open_files_in_dir[0m[0;34m([0m[0mtop[0m[0;34m,[0m [0mwalk[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m     93[0m         [0;32mif[0m [0;32mnot[0m [0mabspath[0m[0;34m:[0m [0mnew[0m[0;34m.[0m[0mtrim_paths[0m[0;34m([0m[0mstart[0m[0;34m=[0m[0mtop[0m[0;34m)[0m[0;34m[0m[0m
[1;32m     94[0m         [0;32mreturn[0m [0mnew[0m[0;34m[0m[0m

[0;32m~/git_repos/abipy/abipy/abio/robots.py[0m in [0;36m_open_files_in_dir[0;34m(cls, top, walk)[0m
[1;32m    136[0m         [0;34m"""Open files in directory tree starting from `top`. Return list of Abinit files."""[0m[0;34m[0m[0m
[1;32m    137[0m         [0;32mif[0m [0;32mnot[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0misdir[0m[0;34m([0m[0mtop[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0m
[0;32m--> 138[0;31m             [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"%s: no such directory"[0m [0;34m%[0m [0mstr[0m[0;34m([0m[0mtop[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m    139[0m         [0;32mfrom[0m [0mabipy[0m[0;34m.[0m[0mabilab[0m [0;32mimport[0m [0mabiopen[0m[0;34m[0m[0m
[1;32m    140[0m         [0mitems[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0m

[0;31mValueError[0m: flow_al_relax_tsmear_nkpt: no such directory
ValueError: flow_al_relax_tsmear_nkpt: no such directory

